---
title:  "Forward"
author: "ORMGP"
date:   "20220125"
output: html_document
knit:   (
            function(input_file, encoding) {
                out_dir <- 'docs';
                rmarkdown::render(
                    input_file,
                    encoding=encoding,
                    output_file=file.path(dirname(input_file), out_dir, 'forward.html')
                )
            }
        )
---

#Forward

The CAMC/YPDT Groundwater Management Program (now the Oakridges Moraine Groundwater Program - ORMGP), initiated in 2001, continues to provide, to thirteen partner agencies, technical support in the form of a comprehensive database, geological and hydrogeological interpretation, and an understanding of groundwater flow systems through the use of groundwater flow models.

The main components of the program are refined as more information becomes available.

The database is the foundation for much of the groundwater work that is being undertaken by the partner agencies.  It has been designed to store a wide variety of information pertaining to water resources across the Oak Ridges Moraine (ORM) area, and to make this data readily accessible to water managers.  The purpose is to create a single source for the information required to fully understand and manage the water that moves through the watersheds draining off of the Oak Ridges Moraine.  The database has grown from its roots of the Ministry of the Environment (MOE)'s Water Well Record Database to include many other data such as Oil and Gas wells, UGAIS wells (MNDM), geotechnical boreholes and test wells; stream data (both flows and quality), climate data and scanned copies of technical reports.  The database continues to grow, with new data being incorporated and identified data gaps successively filled in.

The enclosed report provides a summary of the collection and organization of a significant amount of data that has been collated to facilitate water resources management initiatives.  

Steve Holysh			
Oakridges Moraine Groundwater Program (ORMGP) - Manager
(sholysh@owrc.ca; 416-661-6600 x5588)

 
Rick Gerber
Oakridges Moraine Groundwater Program (ORMGP) - Manager
(rgerber@owrc.ca; 416-661-6600 x5589)

